apiVersion: v1
kind: Service
metadata:
  name: hate-speech-detector-service
spec:
  selector:
    app: hate-speech-detector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
