name: Build and push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: hate-speech-detector

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Run tests
      - name: Run Tests
        run: pytest

      # Set up Docker environment
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Log in to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: your-ecr-registry
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Build and push Docker image to AWS ECR
      - name: Build and Push Docker Image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            804615157644.dkr.ecr.eu-west-3.amazonaws.com/hate_speech_detector/${{ env.IMAGE_NAME }}:${{ github.sha }}
            804615157644.dkr.ecr.eu-west-3.amazonaws.com/hate_speech_detector/${{ env.IMAGE_NAME }}:latest
        secrets:
          docker_username: ${{ secrets.AWS_ACCESS_KEY }}
          docker_password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Get the Docker image digest
      - name: Get Docker Image Digest
        id: image-digest
        run: echo ${{ steps.build-image.outputs.digest }}

      # Print the Docker image digest
      - name: Print Docker Image Digest
        run: echo "Docker image digest is ${{ steps.image-digest.outputs.digest }}"
